# Generated by Django 5.2.6 on 2025-09-19 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="My Resume", max_length=200)),
                ("raw_text", models.TextField(blank=True, default="")),
                (
                    "upload",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RewriteResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_role", models.CharField(max_length=120)),
                ("job_description", models.TextField(blank=True, default="")),
                ("tone", models.CharField(default="professional", max_length=32)),
                ("provider", models.CharField(default="DummyProvider", max_length=128)),
                ("output_text", models.TextField()),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="resume.resume",
                    ),
                ),
            ],
        ),
    ]
