# Generated by Django 5.2.6 on 2025-09-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_created_at", models.DateTimeField(auto_now_add=True)),
                ("log_updated_at", models.DateTimeField(auto_now=True)),
                ("log_content", models.TextField()),
            ],
        ),
    ]
