# Generated by Django 5.2.6 on 2025-09-19 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
